apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-mme-config
  labels:
    epc-mode: mme
data:
  mme.yaml: |
    logger:
      file: /var/log/open5gs/mme.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    mme:
      freeDiameter: /etc/freeDiameter/mme.conf
      s1ap:
        server:
          - address: 0.0.0.0
      gtpc:
        server:
          - address: 0.0.0.0
        client:
          sgwc:
            - address: open5gs-sgwc
          smf:
            - address: open5gs-smf
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
      gummei:
        - plmn_id:
            mcc: {{ .Values.core.mcc }}
            mnc: {{ .Values.core.mnc }}
          mme_gid: 2
          mme_code: 1
      tai:
        - plmn_id:
            mcc: {{ .Values.core.mcc }}
            mnc: {{ .Values.core.mnc }}
          tac: 1
      security:
        integrity_order : [ EIA2, EIA1, EIA0 ]
        ciphering_order : [ EEA0, EEA1, EEA2 ]
      network_name:
        full: Open5GS
        short: Next
      mme_name: open5gs-mme0
      time:
    #    t3402:
    #      value: 720   # 12 minutes * 60 = 720 seconds
    #    t3412:
    #      value: 3240  # 54 minutes * 60 = 3240 seconds
    #    t3423:
    #      value: 720   # 12 minutes * 60 = 720 seconds