apiVersion: v1
kind: Service
metadata:
  name: open5gs-mme
  labels:
    epc-mode: mme
spec:
  selector:
    epc-mode: mme
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777 
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-mme-deployment  
  labels:
    epc-mode: mme
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: mme
  template:
    metadata:
      labels:
        epc-mode: mme
    spec:   
      containers:
        - name: mme
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-mmed", "-c", "/open5gs/config-map/mme.yaml"]
          volumeMounts:
          - name: open5gs-mme-config
            mountPath: /open5gs/config-map/mme.yaml
            subPath: "mme.yaml"          
      volumes:
        - name: open5gs-mme-config
          configMap:
            name: open5gs-mme-config           
