apiVersion: v1
kind: Service
metadata:
  name: open5gs-sepp
  labels:
    epc-mode: sepp
spec:
  selector:
    epc-mode: sepp
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-sepp-deployment
  labels:
    epc-mode: sepp
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: sepp
  template:
    metadata:
      labels:
        epc-mode: sepp
    spec:  
      containers:
        - name: sepp
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-seppd", "-c", "/open5gs/config-map/sepp1.yaml"]
          volumeMounts:
            - name: open5gs-sepp-config
              mountPath: /open5gs/config-map/sepp1.yaml
              subPath: "sepp1.yaml"
      volumes:
        - name: open5gs-sepp-config
          configMap:
            name: open5gs-sepp-config

