apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sepp-config
  labels:
    epc-mode: sepp
data:
  sepp1.yaml: |
    logger:
      file: /var/log/open5gs/sepp1.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    sepp:
      default:
        tls:
          server:
            private_key: /etc/open5gs/tls/sepp1.key
            cert: /etc/open5gs/tls/sepp1.crt
          client:
            cacert: /etc/open5gs/tls/ca.crt
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
    #      nrf:
    #        - uri: http://127.0.0.10:7777
          scp:
            - uri: http://open5gs-scp:7777
      n32:
        server:
          - sender: sepp1.localdomain
        #    scheme: https
        #    address: 127.0.0.1
        #    port: 7777
            # n32f:
            #   scheme: https
            #   address: 127.0.0.2
            #   port: 7777
        # client:
        #   sepp:
        #     - receiver: sepp2.localdomain
        #       uri: https://sepp2.localdomain:7777
        #       resolve: 127.0.2.251
        #       n32f:
        #         uri: https://sepp2.localdomain:7777
        #         resolve: 127.0.2.252