apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwc
  labels:
    epc-mode: sgwc
spec:
  selector:
    epc-mode: sgwc
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-sgwc-deployment
  labels:
    epc-mode: sgwc
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: sgwc
  template:
    metadata:
      labels:
        epc-mode: sgwc
    spec:  
      containers:
        - name: sgwc
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-sgwcd", "-c", "/open5gs/config-map/sgwc.yaml"]
          volumeMounts:
            - name: open5gs-sgwc-config
              mountPath: /open5gs/config-map/sgwc.yaml
              subPath: "sgwc.yaml"
      volumes:
        - name: open5gs-sgwc-config
          configMap:
            name: open5gs-sgwc-config

