apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwu
  labels:
    epc-mode: sgwu
spec:
  selector:
    epc-mode: sgwu
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-sgwu-deployment
  labels:
    epc-mode: sgwu
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: sgwu
  template:
    metadata:
      labels:
        epc-mode: sgwu
    spec:  
      containers:
        - name: sgwu
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-sgwud", "-c", "/open5gs/config-map/sgwu.yaml"]
          volumeMounts:
            - name: open5gs-sgwu-config
              mountPath: /open5gs/config-map/sgwu.yaml
              subPath: "sgwu.yaml"
      volumes:
        - name: open5gs-sgwu-config
          configMap:
            name: open5gs-sgwu-config

