apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwu-config
  labels:
    epc-mode: sgwu
data:
  sgwu.yaml: |
    logger:
      file: /var/log/open5gs/sgwu.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    sgwu:
      pfcp:
        server:
          - address: 0.0.0.0
        client:
    #      sgwc:    # SGW-U PFCP Client try to associate SGW-C PFCP Server
    #        - address: 127.0.0.3
      gtpu:
        server:
          - address: 0.0.0.0