apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
      file: /var/log/open5gs/smf.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
          scp:
            - uri: http://open5gs-scp:7777
      pfcp:
        server:
          - address: 0.0.0.0
        client:
          upf:
            - uri: http://open5gs-upf:7777
              dnn: {{ .Values.dnn }}
      gtpc:
        server:
          - address: 0.0.0.0
      gtpu:
        server:
          - address: 0.0.0.0
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
      session:
        - subnet: 10.45.0.1/16
        - subnet: 2001:db8:cafe::1/48
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      mtu: 1400
    #  p-cscf:
    #    - 127.0.0.1
    #    - ::1
    #  ctf:
    #    enabled: auto   # auto(default)|yes|no
      freeDiameter: /etc/freeDiameter/smf.conf
